//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


/// <summary>
/// Not connected
/// </summary>
namespace FINAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int E_ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> Password { get; set; }
    }
}
